### ISSUE TITLE
batch_processing benchmark

### ISSUE THREAD

**Issue by ZedongPeng** [SECQUOIA/gdplib#30]
Output

```
Benchmarking instance: batch_processing
Traceback (most recent call last):
  File "/local/scratch/a/peng372/github/gdplib/benchmark.py", line 109, in <module>
    benchmark(model, strategy, timelimit, result_dir)
  File "/local/scratch/a/peng372/github/gdplib/benchmark.py", line 34, in benchmark
    TransformationFactory(strategy).apply_to(model)
  File "/local/scratch/a/peng372/anaconda3/lib/python3.11/site-packages/pyomo/core/base/transformation.py", line 77, in apply_to
    reverse_token = self._apply_to(model, **kwds)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/local/scratch/a/peng372/anaconda3/lib/python3.11/site-packages/pyomo/gdp/plugins/hull.py", line 245, in _apply_to
    self._apply_to_impl(instance, **kwds)
  File "/local/scratch/a/peng372/anaconda3/lib/python3.11/site-packages/pyomo/gdp/plugins/hull.py", line 272, in _apply_to_impl
    self._transform_disjunctionData(
  File "/local/scratch/a/peng372/anaconda3/lib/python3.11/site-packages/pyomo/gdp/plugins/hull.py", line 410, in _transform_disjunctionData
    self._transform_disjunct(
  File "/local/scratch/a/peng372/anaconda3/lib/python3.11/site-packages/pyomo/gdp/plugins/hull.py", line 542, in _transform_disjunct
    self._declare_disaggregated_var_bounds(
  File "/local/scratch/a/peng372/anaconda3/lib/python3.11/site-packages/pyomo/gdp/plugins/hull.py", line 617, in _declare_disaggregated_var_bounds
    raise GDP_Error(
pyomo.gdp.disjunct.GDP_Error: Variables that appear in disjuncts must be bounded in order to use the hull transformation! Missing bound for batchSize_log[A,1].
```

**Comment by AlbertLee125** [comment]
```
batch sizes:
Product A, Stage 1: 6.773442941374539
Product A, Stage 2: 6.773442941374539
Product A, Stage 3: 5.909249033528863
Product A, Stage 4: 6.346838370094754
Product A, Stage 5: 6.352229476298235
Product A, Stage 6: 6.520080028386841
Product A, Stage 7: 6.452229476298228
Product A, Stage 8: 6.452229476298228
Product A, Stage 9: 6.452229476298235
Product A, Stage 10: 6.565803576596293
Product B, Stage 1: 7.202495779566587
Product B, Stage 2: 7.202495779566587
Product B, Stage 3: 7.202495779566588
Product B, Stage 4: 6.812298143589214
Product B, Stage 5: 6.956749906160052
Product B, Stage 6: 6.593844412470684
Product B, Stage 7: 6.979352228252377
Product B, Stage 8: 6.979352228252377
Product B, Stage 9: 6.979352228252377
Product B, Stage 10: 5.980739939584221
Product C, Stage 1: 7.035441694903422
Product C, Stage 2: 7.035441694903422
Product C, Stage 3: 6.489679956254805
Product C, Stage 4: 6.755139729749271
Product C, Stage 5: 6.952303478202918
Product C, Stage 6: 6.990453816683737
Product C, Stage 7: 6.39730663612379
Product C, Stage 8: 6.39730663612379
Product C, Stage 9: 6.39730663612379
Product C, Stage 10: 6.979352228252377
Product D, Stage 1: 6.190591169650954
Product D, Stage 2: 6.190591169650954
Product D, Stage 3: 6.327755370786221
Product D, Stage 4: 6.268914870763288
Product D, Stage 5: 6.797759000031957
Product D, Stage 6: 6.298767833912969
Product D, Stage 7: 6.799541694341899
Product D, Stage 8: 6.799541694341899
Product D, Stage 9: 6.799541694341899
Product D, Stage 10: 5.863449762655123
Product E, Stage 1: 6.112483914332051
Product E, Stage 2: 6.112483914332051
Product E, Stage 3: 6.631277707747219
Product E, Stage 4: 6.531996178435062
Product E, Stage 5: 7.097673182668023
Product E, Stage 6: 6.890453816683737
Product E, Stage 7: 6.725433722188179
Product E, Stage 8: 6.725433722188179
Product E, Stage 9: 6.725433722188179
Product E, Stage 10: 5.726821433520012
Product F, Stage 1: 6.503501726693317
Product F, Stage 2: 6.503501726693317
Product F, Stage 3: 5.404889438025153
Product F, Stage 4: 6.303501726693318
Product F, Stage 5: 6.966595779005069
Product F, Stage 6: 6.544177579965901
Product F, Stage 7: 6.33418090596659
Product F, Stage 8: 6.33418090596659
Product F, Stage 9: 6.334180905966522
Product F, Stage 10: 5.49797986109122
Product G, Stage 1: 7.202495779566588
Product G, Stage 2: 7.202495779566588
Product G, Stage 3: 7.102495779566595
Product G, Stage 4: 6.20388349089843
Product G, Stage 5: 5.849338473217522
Product G, Stage 6: 6.947950761885687
Product G, Stage 7: 6.511859621890185
Product G, Stage 8: 6.511859621890185
Product G, Stage 9: 6.511859621890185
Product G, Stage 10: 6.142325597899051
Product H, Stage 1: 6.602737104141064
Product H, Stage 2: 6.602737104141064
Product H, Stage 3: 5.890200838558167
Product H, Stage 4: 5.718267123074469
Product H, Stage 5: 6.816879411742633
Product H, Stage 6: 6.668870192556274
Product H, Stage 7: 6.321557974512607
Product H, Stage 8: 6.321557974512607
Product H, Stage 9: 6.321557974512607
Product H, Stage 10: 6.371568395087269
Product HH, Stage 1: 6.30042346343023
Product HH, Stage 2: 6.30042346343023
Product HH, Stage 3: 5.814915647648529
Product HH, Stage 4: 5.875540269464963
Product HH, Stage 5: 6.826516559327009
Product HH, Stage 6: 5.727904270658844
Product HH, Stage 7: 6.511859621890119
Product HH, Stage 8: 6.511859621890119
Product HH, Stage 9: 6.511859621890119
Product HH, Stage 10: 5.413247333220136
Product HHH, Stage 1: 5.980493426743628
Product HHH, Stage 2: 5.980493426743628
Product HHH, Stage 3: 5.640167620806425
Product HHH, Stage 4: 5.575028318635409
Product HHH, Stage 5: 6.673640607303573
Product HHH, Stage 6: 5.575028318635409
Product HHH, Stage 7: 6.335968955426454
Product HHH, Stage 8: 6.335968955426454
Product HHH, Stage 9: 6.335968955426454
Product HHH, Stage 10: 5.396545538148675
```
I debugged the problem and figured out that model.batchSize_log caused the error on the hull transformation because there were no bounds. This is the benchmark's result printing the logarithm of the batch size for every element and stage. The issue can be resolved by setting the bounds, as shown below.

```
model.batchSize_log = Var(
        model.PRODUCTS, model.STAGES, bounds=(-10,10), doc='Logarithmic Batch Size of the Products'
    ) # added bounds on the model
```
  I am writing about this issue because I want to determine whether these bounds are too loose or not.
