### ISSUE TITLE
BigM: TypeError: 'int' object is not iterable

### ISSUE THREAD

**Issue by ZedongPeng** [SECQUOIA/gdplib#31]
The bigM `TypeError: 'int' object is not iterable` error came up in `biofuel` model.

`biofuel` Output:
```
Benchmarking instance: biofuel
ERROR: Constructing component 'bigM' from data=None failed:
        TypeError: 'int' object is not iterable
Traceback (most recent call last):
  File "/local/scratch/a/peng372/github/gdplib/benchmark.py", line 106, in <module>
    model = import_module("gdplib." + instance).build_model()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/local/scratch/a/peng372/github/gdplib/gdplib/biofuel/model.py", line 55, in build_model
    m.bigM = Suffix(direction=Suffix.LOCAL, initialize=7000)
    ^^^^^^
  File "/local/scratch/a/peng372/anaconda3/lib/python3.11/site-packages/pyomo/core/base/block.py", line 571, in __setattr__
    self.add_component(name, val)
  File "/local/scratch/a/peng372/anaconda3/lib/python3.11/site-packages/pyomo/core/base/block.py", line 1116, in add_component
    val.construct(data)
  File "/local/scratch/a/peng372/anaconda3/lib/python3.11/site-packages/pyomo/core/base/disable_methods.py", line 124, in construct
    return base.construct(self, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/local/scratch/a/peng372/anaconda3/lib/python3.11/site-packages/pyomo/core/base/suffix.py", line 244, in construct
    self.update_values(rule(self.parent_block(), None), expand=True)
  File "/local/scratch/a/peng372/anaconda3/lib/python3.11/site-packages/pyomo/core/base/suffix.py", line 295, in update_values
    for component, value in items:
TypeError: 'int' object is not iterable
```

**Comment by AlbertLee125** [comment]
I think this issue is ready to be closed.
