### ISSUE TITLE
build_model missing

### ISSUE THREAD

**Issue by ZedongPeng** [SECQUOIA/gdplib#33]
There might be two cases.
1. `build_model` function is missing.
2. `__init__.py` file is not updated.

- [x] HDA @parkyr 
```
Benchmarking instance: hda
Traceback (most recent call last):
  File "/local/scratch/a/peng372/github/gdplib/benchmark.py", line 106, in <module>
    model = import_module("gdplib." + instance).build_model()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'gdplib.hda' has no attribute 'build_model'
```

- [x] logical @AlbertLee125 
```
Benchmarking instance: logical
Traceback (most recent call last):
  File "/local/scratch/a/peng372/github/gdplib/benchmark.py", line 106, in <module>
    model = import_module("gdplib." + instance).build_model()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'gdplib.logical' has no attribute 'build_model'
```

- [x] methanol
```
Benchmarking instance: methanol
Traceback (most recent call last):
  File "/local/scratch/a/peng372/github/gdplib/benchmark.py", line 106, in <module>
    model = import_module("gdplib." + instance).build_model()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'gdplib.methanol' has no attribute 'build_model'
```

- [x] mod_hens
```
Benchmarking instance: mod_hens
Traceback (most recent call last):
  File "/local/scratch/a/peng372/github/gdplib/benchmark.py", line 106, in <module>
    model = import_module("gdplib." + instance).build_model()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'gdplib.mod_hens' has no attribute 'build_model'
```

- [x] modprodnet
```
Benchmarking instance: modprodnet
Traceback (most recent call last):
  File "/local/scratch/a/peng372/github/gdplib/benchmark.py", line 106, in <module>
    model = import_module("gdplib." + instance).build_model()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'gdplib.modprodnet' has no attribute 'build_model'
```

**Comment by ZedongPeng** [comment]
We might need to separate the `positioning.py` and `spectralog.py` in `logical` into two folders. Any ideas about this? @bernalde @AlbertLee125

**Comment by bernalde** [comment]
Yes, good idea.
